packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/cli': ^1.4.21
  '@cloudflare/vite-plugin': ^1.26.1
  '@cloudflare/workers-types': ^4.20260307.1
  '@t3-oss/env-core': ^0.13.10
  '@tailwindcss/vite': ^4.2.1
  '@tanstack/devtools-vite': ^0.5.3
  '@tanstack/eslint-config': ^0.4.0
  '@tanstack/match-sorter-utils': ^8.19.4
  '@tanstack/react-devtools': ^0.9.10
  '@tanstack/react-form': ^1.28.4
  '@tanstack/react-form-devtools': ^0.2.17
  '@tanstack/react-form-start': ^1.28.4
  '@tanstack/react-query': ^5.90.21
  '@tanstack/react-query-devtools': ^5.91.3
  '@tanstack/react-router': ^1.166.6
  '@tanstack/react-router-devtools': ^1.166.6
  '@tanstack/react-router-ssr-query': ^1.166.6
  '@tanstack/react-start': ^1.166.6
  '@tanstack/react-table': ^8.21.3
  '@tanstack/router-plugin': ^1.166.6
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.2
  '@types/node': ^25.4.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@uidotdev/usehooks': ^2.4.1
  '@unpic/react': ^1.0.2
  '@vitejs/plugin-react': ^5.1.4
  babel-plugin-react-compiler: ^1.0.0
  better-auth: ^1.5.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dompurify: ^3.3.2
  dotenv: ^17.3.1
  drizzle-orm: ^0.45.1
  drizzle-zod: ^0.8.3
  eslint: ^10.0.3
  jsdom: ^28.1.0
  lucide-react: ^0.577.0
  prettier-plugin-tailwindcss: ^0.7.2
  react: ^19.2.4
  react-dom: ^19.2.4
  simple-icons: ^16.11.0
  solid-js: ^1.9.11
  sonner: ^2.0.7
  tailwindcss: ^4.2.1
  tsx: ^4.21.0
  typescript: ^5.9.3
  uuid: ^13.0.0
  vite: npm:rolldown-vite@latest
  vite-tsconfig-paths: ^6.1.1
  vitest: ^4.0.18
  web-vitals: ^5.1.0
  wrangler: ^4.71.0
  zod: ^4.3.6

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - '@prisma/client'
  - better-sqlite3
  - core-js-pure

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw
  - sharp
  - unrs-resolver
  - workerd
