/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSignoutRouteImport } from './routes/(auth)/signout'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as appProfileIndexRouteImport } from './routes/(app)/profile/index'
import { Route as appLinkRemovedIndexRouteImport } from './routes/(app)/link-removed/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignoutRoute = authSignoutRouteImport.update({
  id: '/(auth)/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileIndexRoute = appProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => appRouteRoute,
} as any)
const appLinkRemovedIndexRoute = appLinkRemovedIndexRouteImport.update({
  id: '/link-removed/',
  path: '/link-removed/',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof authSigninRoute
  '/signout': typeof authSignoutRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/link-removed/': typeof appLinkRemovedIndexRoute
  '/profile/': typeof appProfileIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof authSigninRoute
  '/signout': typeof authSignoutRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/link-removed': typeof appLinkRemovedIndexRoute
  '/profile': typeof appProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signout': typeof authSignoutRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/': typeof appIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/link-removed/': typeof appLinkRemovedIndexRoute
  '/(app)/profile/': typeof appProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/signout'
    | '/signup'
    | '/'
    | '/api/auth/$'
    | '/link-removed/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signout'
    | '/signup'
    | '/'
    | '/api/auth/$'
    | '/link-removed'
    | '/profile'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)/signin'
    | '/(auth)/signout'
    | '/(auth)/signup'
    | '/(app)/'
    | '/api/auth/$'
    | '/(app)/link-removed/'
    | '/(app)/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authSigninRoute: typeof authSigninRoute
  authSignoutRoute: typeof authSignoutRoute
  authSignupRoute: typeof authSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signout': {
      id: '/(auth)/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof authSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile/': {
      id: '/(app)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof appProfileIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/link-removed/': {
      id: '/(app)/link-removed/'
      path: '/link-removed'
      fullPath: '/link-removed/'
      preLoaderRoute: typeof appLinkRemovedIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appLinkRemovedIndexRoute: typeof appLinkRemovedIndexRoute
  appProfileIndexRoute: typeof appProfileIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appLinkRemovedIndexRoute: appLinkRemovedIndexRoute,
  appProfileIndexRoute: appProfileIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authSigninRoute: authSigninRoute,
  authSignoutRoute: authSignoutRoute,
  authSignupRoute: authSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
