/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSignoutRouteImport } from './routes/(auth)/signout'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as apppagesRouteRouteImport } from './routes/(app)/(pages)/route'
import { Route as apppagesIndexRouteImport } from './routes/(app)/(pages)/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appsplashLinkRemovedIndexRouteImport } from './routes/(app)/(splash)/link-removed/index'
import { Route as apppagesProfileIndexRouteImport } from './routes/(app)/(pages)/profile/index'
import { Route as apppagesListIndexRouteImport } from './routes/(app)/(pages)/list/index'
import { Route as apppagesListIdRouteImport } from './routes/(app)/(pages)/list/$id'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignoutRoute = authSignoutRouteImport.update({
  id: '/(auth)/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const apppagesRouteRoute = apppagesRouteRouteImport.update({
  id: '/(pages)',
  getParentRoute: () => appRouteRoute,
} as any)
const apppagesIndexRoute = apppagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => apppagesRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appsplashLinkRemovedIndexRoute =
  appsplashLinkRemovedIndexRouteImport.update({
    id: '/(splash)/link-removed/',
    path: '/link-removed/',
    getParentRoute: () => appRouteRoute,
  } as any)
const apppagesProfileIndexRoute = apppagesProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => apppagesRouteRoute,
} as any)
const apppagesListIndexRoute = apppagesListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => apppagesRouteRoute,
} as any)
const apppagesListIdRoute = apppagesListIdRouteImport.update({
  id: '/list/$id',
  path: '/list/$id',
  getParentRoute: () => apppagesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof authSigninRoute
  '/signout': typeof authSignoutRoute
  '/signup': typeof authSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof apppagesIndexRoute
  '/list/$id': typeof apppagesListIdRoute
  '/list/': typeof apppagesListIndexRoute
  '/profile/': typeof apppagesProfileIndexRoute
  '/link-removed/': typeof appsplashLinkRemovedIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof authSigninRoute
  '/signout': typeof authSignoutRoute
  '/signup': typeof authSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof apppagesIndexRoute
  '/list/$id': typeof apppagesListIdRoute
  '/list': typeof apppagesListIndexRoute
  '/profile': typeof apppagesProfileIndexRoute
  '/link-removed': typeof appsplashLinkRemovedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/(pages)': typeof apppagesRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signout': typeof authSignoutRoute
  '/(auth)/signup': typeof authSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/(pages)/': typeof apppagesIndexRoute
  '/(app)/(pages)/list/$id': typeof apppagesListIdRoute
  '/(app)/(pages)/list/': typeof apppagesListIndexRoute
  '/(app)/(pages)/profile/': typeof apppagesProfileIndexRoute
  '/(app)/(splash)/link-removed/': typeof appsplashLinkRemovedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/signout'
    | '/signup'
    | '/api/auth/$'
    | '/'
    | '/list/$id'
    | '/list/'
    | '/profile/'
    | '/link-removed/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signout'
    | '/signup'
    | '/api/auth/$'
    | '/'
    | '/list/$id'
    | '/list'
    | '/profile'
    | '/link-removed'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/(pages)'
    | '/(auth)/signin'
    | '/(auth)/signout'
    | '/(auth)/signup'
    | '/api/auth/$'
    | '/(app)/(pages)/'
    | '/(app)/(pages)/list/$id'
    | '/(app)/(pages)/list/'
    | '/(app)/(pages)/profile/'
    | '/(app)/(splash)/link-removed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authSigninRoute: typeof authSigninRoute
  authSignoutRoute: typeof authSignoutRoute
  authSignupRoute: typeof authSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signout': {
      id: '/(auth)/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof authSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(pages)': {
      id: '/(app)/(pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof apppagesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(pages)/': {
      id: '/(app)/(pages)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof apppagesIndexRouteImport
      parentRoute: typeof apppagesRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(splash)/link-removed/': {
      id: '/(app)/(splash)/link-removed/'
      path: '/link-removed'
      fullPath: '/link-removed/'
      preLoaderRoute: typeof appsplashLinkRemovedIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(pages)/profile/': {
      id: '/(app)/(pages)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof apppagesProfileIndexRouteImport
      parentRoute: typeof apppagesRouteRoute
    }
    '/(app)/(pages)/list/': {
      id: '/(app)/(pages)/list/'
      path: '/list'
      fullPath: '/list/'
      preLoaderRoute: typeof apppagesListIndexRouteImport
      parentRoute: typeof apppagesRouteRoute
    }
    '/(app)/(pages)/list/$id': {
      id: '/(app)/(pages)/list/$id'
      path: '/list/$id'
      fullPath: '/list/$id'
      preLoaderRoute: typeof apppagesListIdRouteImport
      parentRoute: typeof apppagesRouteRoute
    }
  }
}

interface apppagesRouteRouteChildren {
  apppagesIndexRoute: typeof apppagesIndexRoute
  apppagesListIdRoute: typeof apppagesListIdRoute
  apppagesListIndexRoute: typeof apppagesListIndexRoute
  apppagesProfileIndexRoute: typeof apppagesProfileIndexRoute
}

const apppagesRouteRouteChildren: apppagesRouteRouteChildren = {
  apppagesIndexRoute: apppagesIndexRoute,
  apppagesListIdRoute: apppagesListIdRoute,
  apppagesListIndexRoute: apppagesListIndexRoute,
  apppagesProfileIndexRoute: apppagesProfileIndexRoute,
}

const apppagesRouteRouteWithChildren = apppagesRouteRoute._addFileChildren(
  apppagesRouteRouteChildren,
)

interface appRouteRouteChildren {
  apppagesRouteRoute: typeof apppagesRouteRouteWithChildren
  appsplashLinkRemovedIndexRoute: typeof appsplashLinkRemovedIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  apppagesRouteRoute: apppagesRouteRouteWithChildren,
  appsplashLinkRemovedIndexRoute: appsplashLinkRemovedIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authSigninRoute: authSigninRoute,
  authSignoutRoute: authSignoutRoute,
  authSignupRoute: authSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
